button:
  - platform: shutdown
    name: Shutdown

  - platform: restart
    name: Restart

  - platform: template
    name: Refresh Screen
    icon: mdi:refresh
    entity_category: config
    on_press:
      - script.execute: update_screen