esphome:
  name: ${name}-booking-display
  on_boot:
    priority: -100
    then:
      - light.turn_on:
          id: occupied_light
          red: 0%
          green: 0%
          blue: 80%
          effect: Scan
      - logger.log: "Booting up..."
      - script.execute: actual_update