light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO27
    num_leds: 28
    rmt_channel: 0
    chipset: WS2812
    name: "Occupied Light"
    id: occupied_light
    effects:
      - addressable_scan:
          name: Scan
          move_interval: 50ms
          scan_width: 3