sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    id: wifistrength
    icon: mdi:wifi-strength-2
    internal: false
    update_interval: 120s
    
  - platform: template
    name: Recorded Display Refresh
    accuracy_decimals: 0
    unit_of_measurement: "Refreshes"
    state_class: "total_increasing"
    entity_category: "diagnostic"
    icon: mdi:counter
    lambda: 'return id(recorded_display_refresh);'
