text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
      id: ipaddress
    ssid:
      name: ESP Connected SSID
      id: ssid
    mac_address:
      name: ESP Mac Wifi Address
      id: macaddress

  - platform: mqtt_subscribe
    name: "Upcoming Calendar Events"
    id: calevents
    topic: ${eventsTopic}
    on_value: 
      then:
        - script.execute: update_screen

  - platform: template
    name: Display Last Update
    device_class: timestamp
    entity_category: "diagnostic"
    id: display_last_update