text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
      id: ipaddress
      icon: mdi:ip
    ssid:
      name: ESP Connected SSID
      id: ssid
      icon: mdi:wifi
    mac_address:
      name: ESP Mac Wifi Address
      id: macaddress
      icon: mdi:chip

  - platform: mqtt_subscribe
    name: "Upcoming Calendar Events"
    id: calevents
    topic: ${eventsTopic}
    icon: mdi:calendar
    internal: true
    web_server:
      sorting_weight: 0
    on_value: 
      then:
        - script.execute: data_received
    
  - platform: template
    name: "Last Message"
    id: last_message
    icon: mdi:calendar
    update_interval: never
    web_server:
      sorting_weight: 1

  - platform: template
    name: "Index 0 Start Time"
    id: index0_start_time
    icon: mdi:clock
    internal: true
    update_interval: never
    web_server:
      sorting_weight: 2

  - platform: template
    name: "Index 0 End Time"
    id: index0_end_time
    icon: mdi:clock
    internal: true
    update_interval: never
    web_server:
      sorting_weight: 3
  
  - platform: template
    name: Display Last Update
    icon: mdi:clock
    device_class: timestamp
    entity_category: "diagnostic"
    id: display_last_update
    update_interval: never
    lambda: |-
      char buffer[17];
      time_t currTime = id(esptime).now().timestamp;
      strftime(buffer, sizeof(buffer), "%Y-%m-%dT%H:%M", localtime(&currTime));
      return std::string(buffer);